# Generated by Django 4.0.4 on 2022-05-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=122)),
                ('empemail', models.EmailField(max_length=122)),
                ('emppass', models.CharField(max_length=20)),
            ],
        ),
    ]
