# Generated by Django 4.0.4 on 2022-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login_userimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userimg',
            field=models.ImageField(blank=True, default='media/image.jpg', null=True, upload_to=''),
        ),
    ]
