# Generated by Django 4.0.4 on 2022-05-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='empid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
