# Generated by Django 4.0.4 on 2022-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_session_empid_alter_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
