# Generated by Django 4.0.4 on 2022-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_session_end_alter_session_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='end',
            new_name='entrytime',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
