# Generated by Django 4.0.4 on 2022-05-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_end_session_entrytime_remove_session_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sno',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
