# Generated by Django 4.0.4 on 2022-05-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_session_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='host',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
